[package]
name = "procnuke"
version = "0.2.1"
edition = "2021"
authors = ["Kihau"]
repository = "https://github.com/Kihau/procnuke"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
